name: Build and Deploy Node.js with React Frontend and Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Build frontend
        run: |
          cd frontend
          npm install
          CI=false npm run build

      - name: Install backend dependencies
        run: |
          npm install

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            frontend/build
            server.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  # Ensure this secret exists in your repo
          app_location: "frontend/build"
          api_location: "."
          output_location: "build"
