name: Build and deploy Node.js app to Azure Web App - backend-001

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        working-directory: ./backend  # Ensure only backend files are zipped
        run: zip -r release.zip .  # Zip the current directory (backend)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend/release.zip  # Specify exact path to the ZIP file

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Optional: Uncomment if you need to inspect/modify the ZIP contents
      # - name: Unzip artifact for deployment
      #   run: unzip release.zip

      - name: Delay to Avoid SCM Conflict
        run: sleep 30  # Wait 30 seconds to avoid SCM restart conflicts

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-001'
          slot-name: 'Production'
          package: ./release.zip  # Deploy the ZIP directly
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1538A423DB434915BF49499792B1E04C }}
          clean: true  # Clear previous deployment to avoid conflicts
