name: Build and deploy Node.js app to Azure Web App - backend-001

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present

      - name: Create Deployment Structure
        run: |
          mkdir -p deploy/backend
          cp -r backend/* deploy/backend/
          cd deploy
          zip -r ../release.zip .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-001'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1538A423DB434915BF49499792B1E04C }}
          clean: true
